version: 0.2
phases:
 install:
   runtime-versions:
     nodejs: 18
   commands:
     - echo "Installing Node dependencies..."
     - npm install || true     # optional, in case you use Express or any other packages
 build:
   commands:
     - echo "Build step completed."
artifacts:
 files:
   - appspec.yml
   - server.js
   - index.html
   - scripts/**      # shell scripts
   - css/**          # if you have any CSS folder