version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build phase is skipped because you have only static HTML and Node backend
  post_build:
    commands:
      - echo Build completed - ready for CodeDeploy

artifacts:
  files:
    - '**/*'
  discard-paths: no
