version: 0.2
phases:
 install:
   runtime-versions:
     python: 3.8
   commands:
     - echo "Installing Python dependencies..."
     - pip3 install -r requirements.txt || true  # Optional
 build:
   commands:
     - echo "Build step completed."
artifacts:
 files:
   - '**/*'