version: 0.2
phases:
 install:
   runtime-versions:
     nodejs: 18
   commands:
     - echo Installing Node.js dependencies...
     - npm install
 build:
   commands:
     - echo No build step needed for this Node.js app
 post_build:
   commands:
     - echo Build complete - ready for CodeDeploy
artifacts:
 files:
   - '**/*'
 discard-paths: no